---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptnphpdemo
  labels:
    app: keptnphpdemo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keptnphpdemo
  template:
    metadata:
      labels:
        app: keptnphpdemo
    spec:
      containers:
      - image: "{{ .Values.image }}"
        imagePullPolicy: Always
        name: keptnphpdemo
        env:
          - name: DT_CUSTOM_PROP
            value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
          - name: KEPTN_PROJECT
            value: "{{ .Values.keptn.project }}"
          - name: KEPTN_STAGE
            value: "{{ .Values.keptn.stage }}"
          - name: KEPTN_SERVICE
            value: "{{ .Values.keptn.service }}"
          - name: KEPTN_DEPLOYMENT
            value: "{{ .Values.keptn.deployment }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 25Mi