--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptnphpdemo
  labels:
    app: keptnphpdemo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keptnphpdemo
  template:
    metadata: 
      labels:
        app: keptnphpdemo
    spec:
      containers:
      - image: "{{ .Values.image }}"
        imagePullPolicy: Always
        name: keptnphpdemo
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 25Mi