apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: keptnphpdemo-primary
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: keptnphpdemo-primary
  type: LoadBalancer
status:
  loadBalancer: {}
