apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: keptnphpdemo-canary
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: keptnphpdemo
  type: LoadBalancer
status:
  loadBalancer: {}
