apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: keptnphpdemo
  name: keptnphpdemo-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keptnphpdemo-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keptnphpdemo-primary
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=keptnphpdemo keptn_service=keptnphpdemo keptn_stage=production
            keptn_deployment=primary
        - name: KEPTN_PROJECT
          value: keptnphpdemo
        - name: KEPTN_STAGE
          value: production
        - name: KEPTN_SERVICE
          value: keptnphpdemo
        - name: KEPTN_DEPLOYMENT
          value: canary
        image: core.harbor.domain/keptnphpdemo/keptnphpdemo:1.2
        imagePullPolicy: Always
        name: keptnphpdemo
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
status: {}
